# Alacritty Configuration File

[window]
padding = { x = 0, y = 0 }
decorations = "Full"
decorations_theme_variant = "Dark" 

[font]
normal = { family = "Monaco", style = "Regular" }
bold = { family = "Monaco", style = "Bold" }
italic = { family = "Monaco", style = "Italic" }
bold_italic = { family = "Monaco", style = "Bold Italic" }
size = 16.0

[colors]
[colors.primary]
background = "#000000"
foreground = "#EDEDED"

[colors.cursor]
cursor = "#FFFFFF"
text = "#2B2B2B"

[colors.selection]
text = "#000000"
background = "#8C8CFF"

[colors.normal]
black = "#1e1e1e"   
red = "#ff5555"     
green = "#55ff55"   
yellow = "#ffff55"  
blue = "#5555ff"    
magenta = "#ff55ff" 
cyan = "#55ffff"    
white = "#ffffff"   

[colors.bright]
black = "#666666"
red = "#ff6666"     
green = "#66ff66"   
yellow = "#ffff66"  
blue = "#6666ff"    
magenta = "#ff66ff" 
cyan = "#66ffff"    
white = "#ffffff"   
